### ISSUE TITLE
bulk_adding: 'NoneType' object has no attribute 'source_url'

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/yournextrepresentative#124]
We've been getting quite a lot of these error emails recently:

```
Internal Server Error: /bulk_adding/parl.2017-06-08/WMC:S14000004/
Traceback (most recent call last):
  File "/var/www/ynr/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/ynr/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/ynr/env/local/lib/python2.7/site-packages/braces/views/_access.py", line 64, in dispatch
    request, *args, **kwargs)
  File "/var/www/ynr/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/www/ynr/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/var/www/ynr/code/bulk_adding/views.py", line 68, in get_context_data
    'source': context['official_document'].source_url,
AttributeError: 'NoneType' object has no attribute 'source_url'
```

This is from a GET request with an empty QueryDict.

**Comment by symroe** [comment]
Oh I think this is a dupe (at about the same time!) of #123. Ok if we close this one?

**Comment by mhl** [comment]
Oops, I'll close this.
