### ISSUE TITLE
Deal with patchy 'current' elections in EE importer

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/yournextrepresentative#2116]
### Issue and Steps to Reproduce
```
Traceback (most recent call last):
  File "/var/www/ynr/code/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/ynr/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/var/www/ynr/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/ynr/env/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/ynr/env/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/var/www/ynr/code/ynr/apps/elections/uk/management/commands/uk_create_elections_from_every_election.py", line 119, in handle
    self.import_approved_elections(
  File "/var/www/ynr/code/ynr/apps/elections/uk/management/commands/uk_create_elections_from_every_election.py", line 68, in import_approved_elections
    raise e
  File "/var/www/ynr/code/ynr/apps/elections/uk/management/commands/uk_create_elections_from_every_election.py", line 64, in import_approved_elections
    parent = ee_importer.get_parent(ballot_id)
  File "/var/www/ynr/code/ynr/apps/elections/uk/every_election.py", line 402, in get_parent
    return self.election_tree[child.parent]
KeyError: 'local.belfast.2023-05-18'
```

This error occurs here https://github.com/DemocracyClub/yournextrepresentative/blob/2f4ef50db0788122af44f8a8e07e55db0de3615f/ynr/apps/elections/uk/management/commands/uk_create_elections_from_every_election.py#L68 where the comments indicate the parent is set to `None`(I've confirmed the parent Election exists in the DB). I'm not sure in this case if this error should be ignored.

### Additional Details
* Browser and version
* Were you logged in?

**Comment by symroe** [comment]
What I think happened here:


1. Some elections in EE were marked as `current=True` rather than `current=None`
2. Over the elections, the entire 'tree' was showing up in the API response and YNR was able to build it correctly
3. After the elections, the rolling 'current' window passed for most of the elections, but the ones marked `current=True` continued to show up to YNR
4. Because of this, there wasn't a parent election to find.

I think the error went away because we unmarked `local.belfast.2023-05-18` as current.

The fix is...well, it could be a number of things,

Maybe we don't allow setting `current` on ballots in EE, and then assume all children of a group share its status?

Maybe we get all children of current elections, even when not returned in the initial response?

Maybe we catch this error by seeing that there is only one node in a given tree, and ignore it?

Either way, this isn't a high priority at the moment.
