### ISSUE TITLE
uk_create_elections_from_every_election removes some PostExtraElection associations

### ISSUE THREAD

**Issue by mhl** [DemocracyClub/yournextrepresentative#59]
I was investigating why the fix for https://github.com/DemocracyClub/yournextrepresentative/pull/51 was being immediately undone by `uk_create_elections_from_every_election`.

I believe this is related to some of those posts being linked to more than one election initially. For example, let's look at the the post with label "Anderston/City":

```
In [3]: post = Post.objects.get(label='Anderston/City')

In [4]: post.extra.elections.all()
Out[4]: [<Election: Glasgow by-election: Anderston City ward>, <Election: Glasgow City Council local election>]
```

When importing from EveryElection, this post comes up for `local.glasgow-city.2017-05-04` (from https://elections.democracyclub.org.uk/api/elections?group_type=organisation ) This post is found to exist, but all its `PostExtraElection` objects are deleted by https://github.com/DemocracyClub/yournextrepresentative/blob/67546d98e8fcedd0ba2d75b518188294256badd8/elections/uk/management/commands/uk_create_elections_from_every_election.py#L259-L264 and only `<Election: Glasgow City Council local election>` is put back.

I think the fix here is something like changing those lines to:

```python
PostExtraElection.objects.update_or_create(
    postextra=post_extra,
    election=election,
    defaults={'winner_count': winner_count}
)
```

What do you think, @symroe? I'm not completely confident about what the scope of data coming from Every Election is, so I'm not sure if this the right fix, or a sign of something wrong in the data. (I should have thought about this when reviewing, of course - sorry...)

**Comment by symroe** [comment]
Yes, that seems reasonable. Would you like me to try that out on my local copy?

**Comment by symroe** [comment]
I get the following when running the import with the PRs merged and the changes above made:


```Traceback (most recent call last):
  File "manage.py", line 45, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/symroe/.envs/ynr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/symroe/.envs/ynr/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/symroe/.envs/ynr/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/symroe/.envs/ynr/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/symroe/.envs/ynr/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/Users/symroe/Projects/democracyclub/yournextrepresentative/elections/uk/management/commands/uk_create_elections_from_every_election.py", line 41, in handle
    errors = check_constraints()
  File "/Users/symroe/Projects/democracyclub/yournextrepresentative/candidates/models/constraints.py", line 6, in check_constraints
    return check_paired_models() + check_membership_elections_consistent()
  File "/Users/symroe/Projects/democracyclub/yournextrepresentative/candidates/models/constraints.py", line 64, in check_membership_elections_consistent
    if (post_extra.id, election.id) not in postextra_election_tuples_allowed:
AttributeError: 'NoneType' object has no attribute 'id'```

**Comment by symroe** [comment]
More info: I get this on a parl election, and the NoneType is for `me.election`

**Comment by symroe** [comment]
Sorry, this might be a distraction: I had 78 MemebershipExtra objects in my dev DB without an Election. I expect this was from previous mistakes, nothing to do with this problem.
